version: "3"
services:
    nginx:
        image: nginx
        ports:
            - 9000:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
    flask:
        build:
            context: ./
            dockerfile: Dockerfile
        image: inside-out
        container_name: inside-out
        environment:
            - LOG_FILE=/var/log/request-proxy.log
            - FLAG=DUCTF{very_spooky_request}
            - FLASK_APP=/app/main.py
        command: python -u /app/main.py
