apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{CONTAINER_NAME}} # REPLACE challenge-name and challenge-category to your challenges's name and category
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{CONTAINER_NAME}}
  template:
    metadata:
      labels:
        app: {{CONTAINER_NAME}}
    spec:
      enableServiceLinks: false
      containers:
      - name: {{CONTAINER_NAME}}
        image: gcr.io/{{PROJECT_NAME}}/{{CONTAINER_NAME}}:latest # Set this URL to your challenge container's image
        resources: # Resource limits for the container. These are important, in case people manage to max out CPU/RAM on your challenge
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports: # Port exposed by the container, you can add multiple
        - containerPort: 80
          name: port-80
---
apiVersion: v1
kind: Service
metadata: # Set the challenge-name/challenge-category SAME as the deployment, otherwise they won't link to each other
  name: {{CONTAINER_NAME}}
  labels:
    challenge: {{CONTAINER_NAME}}
spec:
  type: NodePort
  selector:
    app: {{CONTAINER_NAME}}
  ports:
  - port: 80 # The port exposed by the container
    name: port-80
    targetPort: 80 # The port exposed by the container
    nodePort: 30000 # The port that is exposed on each Node on the cluster
