# This is to set up the RBAC for accessing secrets as the default service account in the default namespace.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: lol-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: lol-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lol-role
subjects:
- kind: ServiceAccount
  name: default

---
apiVersion: v1
kind: Secret
metadata:
  name: nooooo-dont-read-me
type: Opaque
data:
  # Base 64 encoded flag
  so-secret-though: RFVDVEZ7ZzAwbmllc19nb3RfdGgxc19sNHN0X3llYXJfbm93X3VfZGlkIX0K